DROP TABLE IF EXISTS BATCH_JOB_TRIGGER_CONFIG;

CREATE TABLE BATCH_JOB_TRIGGER_CONFIG (
    JOB_NAME VARCHAR(50),
    JOB_DESC VARCHAR(150),
    BEAN_NAME VARCHAR(50),
    TRIGGER_NAME VARCHAR(50),
    CRON_TRIGGER VARCHAR(100),
    ENABLE CHAR(1),
    CREATE_ID VARCHAR(10),
    CREATE_DATE DATE,
    UPDATE_ID VARCHAR(10),
    UPDATE_DATE DATE,
    PRIMARY KEY(JOB_NAME)
);
